### ISSUE TITLE
How to use the `example.py`?

### ISSUE THREAD

**Issue by exetico** [dingusdk/PythonIhcSdk#6]
Hi

I'm just trying to get a better knowledge of how to use the library outside Home Assistant.

By cloning the repo, and installing the modules, it's returning the following with python 2.7:
```
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    from ihcsdk.ihccontroller import IHCController
  File "/home/USERNAME_REMOVED/_Testing/PythonIhcSdk/ihcsdk/ihccontroller.py", line 22
    def __init__(self, url: str, username: str, password: str):
```

Executed with python 3.5, it's returning the following error:
```
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    from ihcsdk.ihccontroller import IHCController
  File "/home/USERNAME_REMOVED/_Testing/PythonIhcSdk/ihcsdk/ihccontroller.py", line 39
    f"{url}/wsdl/controller.wsdl", verify=client.connection.cert_verify()
```

I have tried to add the parameters in the execution-command:
`python3 example.py http://IPGOESHERE:5050 Username Password IHCDeviceID`

And by creating the `.parameters`, with no luck, too.

I tried to pull one of the older releases, with no luck, tested with Python 3.5:
```
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    from ihcsdk.ihccontroller import IHCController
  File "/home/USERNAME_REMOVED/_Testing/TestNew/PythonIhcSdk-2.7.1/ihcsdk/ihccontroller.py", line 9, in <module>
    from ihcsdk.ihcclient import IHCSoapClient, IHCSTATE_READY
  File "/home/USERNAME_REMOVED/_Testing/TestNew/PythonIhcSdk-2.7.1/ihcsdk/ihcclient.py", line 311
    f'./SOAP-ENV:Body/ns1:getSystemInfo1/ns1:{param}',
                                                    ^
SyntaxError: invalid syntax
```

**Comment by exetico** [comment]
Om*g...

Note to self: Remember to update Python-env, before moving on. It works just fine with Python 3.9. 👍
